### ISSUE TITLE
Images don't get downloaded

### ISSUE THREAD

**Issue by pgegenfurtner** [mtbottens/gatsby-directus#6]
In my directus data I have entries with single and multiple images. These don't get downloaded and transformed via sharp. 

The advancedImageProcessingEnabled flag is set to true and all required plugins are installed.
When I look into the `.cache` directory, no `directus` folder is present.

**Comment by pgegenfurtner** [comment]
I looked a bit into it and found out that in `image.js` the check `gatsbyImageDoesNotExists`causes the problem.

When I change the check from `return !gatsbyImageDoesNotExist && columnData.ui === 'single_file' && columnData.related_table === 'directus_files';` to `return columnData.ui === 'single_file' && columnData.related_table === 'directus_files';` the download starts.

**Comment by mtbottens** [comment]
@pgegenfurtner Thanks for investigating. I removed this check since the option explicitly turns this on. In the instance that the transformers aren't installed, it should fail silently since they won't need to be transformed.
